defaults:

    - experience: default

    - dataset: sop

    - loss: HAPPIER

    - model: resnet

    - optimizer: sop

    - transform: sop

    - override hydra/job_logging: colorlog

    - override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./

  sweep:
    dir: ${experience.log_dir}
    subdir: ${experience.experiment_name}/outputs
